name: "OUBaC"
description: "Description"

url: "localhost:4000"

paginate: 5
paginate_path: "/latest-news/page:num/"

plugins:
 - jekyll-sitemap
 - jekyll-paginate

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
